### PR TITLE
[110] Update the README.md file

### PR DESCRIPTION
**Pull request by rangareddy**
## *Important Read*

This pull request aims to address issues [#110](https://github.com/onehouseinc/LakeView/issues/110)

## What is the purpose of the pull request

Updated the README.md file by adding sections and update the steps to run.

## Verify this pull request

Checked README.md file and contents looks good.

### CODE REVIEW

**Comment by alberttwong** [comment]
I like it but there a lot of changes.

**Comment by alberttwong** [comment]
@rangareddy can you check the README again?  There is conflicts.

**Comment by rangareddy** [comment]
> @rangareddy can you check the README again? There is conflicts.

Fixed the Merging conflicts. Please review the latest README.md file contnet.

**Comment by alberttwong** [comment]
ci failed

**Comment by rangareddy** [comment]
> ci failed

This could be happen due to SONAR token was expired or became invalid or sonar class issues.  

CC: @pkgajulapalli

**Comment by pkgajulapalli** [comment]
> > ci failed
> 
> This could be happen due to SONAR token was expired or became invalid or sonar class issues.
> 
> CC: @pkgajulapalli

@rangareddy I see the sonar step is working fine in https://github.com/onehouseinc/LakeView/pull/115. Can you please try raising a PR from a different branch in this repo itself?

**Comment by rangareddy** [comment]
Hi @alberttwong 

Raised a new PR by changing the git default origin to onehouse origin. 

https://github.com/onehouseinc/LakeView/pull/117

**Comment by rangareddy** [comment]
Raised a new PR to fix the Sonar build failed Issue i.e [117](https://github.com/onehouseinc/LakeView/pull/117). So closing this PR.

**Pull request closed without merging**
